### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@2.2.0-rc.3

### ISSUE THREAD

**Issue by gruberjl** [soundcloud/chunk-manifest-webpack-plugin#23]
I'm receiving the following during `npm install`

* **error** `UNMET PEER DEPENDENCY webpack@2.2.0-rc.3`
* **warning** `npm WARN chunk-manifest-webpack-plugin@1.0.0 requires a peer of webpack@^2.0.0 but none was installed.`

```
// shortened for clarity
"devDependencies": {
    "chunk-manifest-webpack-plugin": "^1.0.0",
    "webpack": "2.2.0-rc.3"
}
```

I've tested the chunk manifest and it is working. I'm sure I'm missing something obvious causing the error.

**Comment by isthisstackoverflow** [comment]
I've seen this multiple times lately, also without using the plugin here. It seems to be a problem with either webpack or node - no idea, honestly. But afaik the error is not on your end.

**Comment by gruberjl** [comment]
Thanks for the update. I'm using a release candidate on webpack so I'm guessing it's something there. Once Webpack 2.0 is released I'll see if the issue returns.
